### ISSUE TITLE
Kind request to hide package from Atmosphere

### ISSUE THREAD

**Issue by dandv** [cwohlman/meteor-emails-mandrill#1]
Hi @cwohlman,

Looks like this package was published to Atmosphere by mistake. Would you mind hiding it from searches?

```
meteor admin set-unmigrated cwohlman:emails-mandrill
```

Thanks,
Dan
[Atmosphere moderator](https://atmospherejs.com/dandv)

**Comment by cwohlman** [comment]
Done.
